#!/bin/sh

# program name:
PROGRAM=asgl

# executable:
EXECUTABLE=${PROGRAM}_gfortran
# default steering file name for the $PROGRAM:
DEFAULT=${PROGRAM}

# get the argument to the program if none supplied:
if test $# -lt 1
then
  STEERF=${DEFAULT}
else
  STEERF=$1
fi

BIN_ASGL=/usr/bin
LIB_ASGL=/usr/lib/asgl
export BIN_ASGL LIB_ASGL

# for IBM RS6000, to make ERR keyword in I/O work:
cnverr=yes ; export cnverr

# run the program:
# BIN_value/${EXECUTABLE} $STEERF > $LOGF
${LIB_ASGL}/${EXECUTABLE} $STEERF
# nice -20 ${EXECUTABLE} $STEERF
