#!/bin/sh

# program name:
PROGRAM=asgl

# executable:
EXECUTABLE=${PROGRAM}_${ASGL_EXECUTABLE_TYPE}
# default steering file name for the $PROGRAM:
DEFAULT=${PROGRAM}

# get the argument to the program if none supplied:
if test $# -lt 1
then
  STEERF=${DEFAULT}
else
  STEERF=$1
fi

# ASGL binary and library file locations:
BIN_ASGL=BIN_value
LIB_ASGL=LIB_value
export BIN_ASGL LIB_ASGL

# for IBM RS6000, to make ERR keyword in I/O work:
cnverr=yes ; export cnverr

# run the program:
exec ${BIN_ASGL}/${EXECUTABLE} $STEERF
# nice -20 ${EXECUTABLE} $STEERF
