#!/bin/sh

# program name:
PROGRAM=asgl
# the extension for the steering file:
EXT=.top
# the extension for the log file:
LOG=.log

# executable:
EXECUTABLE=${PROGRAM}_${ASGL_EXECUTABLE_TYPE}
# default steering file name for the $PROGRAM:
DEFAULT=${PROGRAM}

# get the argument to the program if none supplied:
if test $# -lt 1
then
  DIR=.
  STEERF=${DEFAULT}
else
  DIR=`dirname $1`
  STEERF=$DIR/`basename $1 ${EXT}`
  # STEERF=`basename $1 ${EXT}`
fi
LOGF=$DIR/`basename $STEERF ${EXT}`${LOG}

# Do not do this because if you just copy the installed PROGRAM from one
# machine to the other it won't work when the installed directories
# are different. Instead, rely on the environment variables defined in 
# setPROGRAM. Maybe this will be problem when using scripts for submitting
# a job to NQS?
#
# BIN_ASGL=BIN_value
# LIB_ASGL=LIB_value
# export BIN_ASGL LIB_ASGL ASGL

# for IBM RS6000, to make ERR keyword in I/O work:
cnverr=yes ; export cnverr

# run the program:
# BIN_value/${EXECUTABLE} $STEERF > $LOGF
${EXECUTABLE} $STEERF > $LOGF
# nice -20 ${EXECUTABLE} $STEERF
